apiVersion: v1
kind: Service
metadata:
  name: bbc-news-service
  labels:
    app: bbc-news-app
    service: bbc-news-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: bbc-news-app